# Generated by Django 5.0.6 on 2024-06-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after_purchase', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('transactions_type', models.IntegerField(blank=True, choices=[(1, 'Deposit'), (2, 'Borrow'), (3, 'Return')], null=True)),
                ('return_book', models.BooleanField(default=False)),
                ('book', models.CharField(default='', max_length=100)),
                ('book_id', models.IntegerField(default=1)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbalanceaccount')),
            ],
        ),
    ]
